[window]
padding ={x = 12, y = 12 }
dynamic_tile = true
opacity = 0.6
decoration = "full"

[scrolling]
history = 10000
mutiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[colors.primary]
background = "#24283b"
foreground = "#c0caf5"

